name: CICD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  security:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:

    needs: security

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the frontend image
      run: cd frontend && npm install && npm run build && cd .. && docker build . -f ./Dockerfile_frontend -t upi05/frontend

    - name: Build the apiserver image
      run: docker build . -f Dockerfile_apiserver -t upi05/apiserver

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: votruongtrunghieu@gmail.com
        password: ${{ secrets.DOCKERHUB_PW }}

    - name: Push images
      run: docker push upi05/frontend && docker push upi05/apiserver

    #- name: CI Badges in case testing
    #  uses: gaelgirodon/ci-badges-action@v1
    #  with:
    #    gist-id: 83254e655024c7a59867a51efdff2525
    #    token: ${{ secrets.GIST_TOKEN }}

    - name: Argocd
      uses: imajeetyadav/argocd-cli@v1
      with:
        version: v2.5.7

    - name: Trigger CD with ArgoCD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWD }} \
        && argocd app sync d1l1th1um --force --replace

