name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build frontend
      run: cd frontend && npm run build
    - name: Build the frontend image
      run: docker build . -f Dockerfile_frontend -t frontend:$(date +%s)
    - name: Build the apiserver image
      run: docker build . -f Dockerfile_apiserver -t apiserver:$(date +%s)